### ISSUE TITLE
Docker ComposeのYAMLファイルからversion属性を削除する

### ISSUE THREAD

**Issue by masiuchi** [movabletype/mt-dev#34]
`make up`を実行すると、下記のような警告が複数出ている。

> WARN[0000] /home/.../mt-dev/mt/common.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion

- version属性はDocker Compose V1では必須だったが、Docker Compose V2で不要になったらしい
  - https://zenn.dev/miroha/articles/whats-docker-compose-v2
- Docker Compose V1は、2023年6月でEOLを迎えている
  - https://www.docker.com/blog/new-docker-compose-v2-and-v1-deprecation/

削除してしまって問題なさそう。

現時点で何か問題出ているわけではなさそうなので、急いで対応する必要はない。

**Comment by usualoma** [comment]
ありがとうございます。

v2.5.1 までは Vagrantfile で v1 を使っていたので残していたのですが、 v2.6.0 で v2 になったので、削除した方がいいですね。対応します。
