### ISSUE TITLE
M2 Macでmake upすると警告が出る

### ISSUE THREAD

**Issue by tomoaki-ito-b** [movabletype/mt-dev#37]
```
 ! mt The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested    0.0s 
 ! httpd The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s 
```

### See also

- [M1搭載MacのDockerでMySQLを動かしてみる](https://gihyo.jp/dev/serial/01/mysql-road-construction-news/0167)
> 表示されている警告は「linux/arm64/v8用のCPUが載っているPC上で、linux/amd64用のコンテナを動かしていてCPUの命令セットが一致してません」という内容になります。

**Comment by usualoma** [comment]
ありがとうございます。

mtとhttpd（apache）を動かしているコンテナは、デフォルトでは以下のMT用のイメージを利用していて、ここにadm64のイメージしかないのが原因です。
https://hub.docker.com/r/movabletype/test

arm64のイメージを作ってdocker hubにpushすれば警告は出なくなるのですが、今のところそこにコストをかける予定はないというところです。（動作上の問題はないので）

「amd64のイメージ以外は使わない」と決めれば以下のような変更もありかもしれません。

```diff
diff --git a/mt/common.yml b/mt/common.yml
index 8def479..a782fe9 100644
--- a/mt/common.yml
+++ b/mt/common.yml
@@ -26,6 +26,7 @@ services:
       - "./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
     labels:
       mt-dev.service: "mt"
+    platform: linux/amd64
 
   httpd:
     build:
@@ -53,6 +54,7 @@ services:
     ports:
       - "${HTTPD_EXPOSE_PORT:-80}:80"
     command: apache2-foreground
+    platform: linux/amd64
 
   mt-watcher:
     build:
```

ただ、httpd などはmovabletype/testだけでななく、 make で `DOCKER_HTTPD_IMAGE=php:8.1-apache` のように指定すれば任意のイメージを使うこともできるので、「amd64のイメージ以外は使わない」と決めてしまいたくないところもあります。（とはいえ、決めてしまっても大きな問題はないのですが）

今のところはknown issueとさせてもらってもいいでしょうか。

**Comment by tomoaki-ito-b** [comment]
はい、それで構わないです！
