### ISSUE TITLE
SSIを使用したい

### ISSUE THREAD

**Issue by rfv-zz** [movabletype/mt-dev#5]
SSIを有効にしたいのですが、その際にはどの部分を変更、記述すれば良いでしょうか？
よろしくお願いいたします。

**Comment by usualoma** [comment]
@rfv-zz フィードバックありがとうございます。これまでは SSI の設定はなかったのですが、開発環境としては常にSSIが有効になっていた方が好ましいと思いますので、 デフォルトで有効になるように変更してリリースしました。
https://github.com/movabletype/mt-dev/releases/tag/v1.0.7

お試しいただければ幸いです。

**Comment by rfv-zz** [comment]
@usualoma 
対応ありがとうございます！
動作するのを確認できました。
助かりました！
